services:
  bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: news_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: пароль БД
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: